"""生成完整的 template_data.py，包含72个模板的专业字段定义"""
import json

# ======== 答辩状通用字段 ========
DEFENSE_BASE = [
    {"name": "respondent_info", "label": "答辩人信息", "type": "object", "required": True, "properties": [
        {"name": "name", "label": "姓名", "type": "text", "required": True},
        {"name": "address", "label": "住址", "type": "text", "required": True},
        {"name": "phone", "label": "联系电话", "type": "text", "required": True},
    ]},
    {"name": "plaintiff_info", "label": "被答辩人信息", "type": "object", "required": True, "properties": [
        {"name": "name", "label": "姓名", "type": "text", "required": True},
        {"name": "address", "label": "住址", "type": "text", "required": True},
    ]},
    {"name": "case_cause", "label": "案由", "type": "text", "required": True, "placeholder": "请输入案由"},
    {"name": "objections", "label": "答辩请求", "type": "array", "required": True, "item": {"type": "text", "label": "答辩请求"}},
    {"name": "fact_and_reason", "label": "事实与理由", "type": "textarea", "required": True, "placeholder": "请详细陈述事实与理由"},
    {"name": "evidence_list", "label": "证据清单", "type": "array", "required": True, "item": {"type": "object", "properties": [
        {"name": "name", "label": "证据名称", "type": "text", "required": True},
        {"name": "content", "label": "证明内容", "type": "text", "required": True},
    ]}},
    {"name": "responding_court", "label": "受理法院", "type": "text", "required": True, "placeholder": "请输入受理法院全称"},
    {"name": "responding_date", "label": "答辩日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
]

# ======== FZ法律援助文书字段 ========
FZ_FIELDS = {
    "FZ-001": [  # 法律援助咨询登记表
        {"name": "consultant_name", "label": "咨询人姓名", "type": "text", "required": True, "placeholder": "请输入咨询人姓名"},
        {"name": "consultant_gender", "label": "咨询人性别", "type": "select", "required": False, "options": [{"value": "男", "label": "男"}, {"value": "女", "label": "女"}]},
        {"name": "consultant_id_no", "label": "身份证号", "type": "text", "required": False, "placeholder": "请输入身份证号"},
        {"name": "consultant_phone", "label": "联系电话", "type": "text", "required": True, "placeholder": "请输入联系电话"},
        {"name": "consultation_date", "label": "咨询日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
        {"name": "consultation_content", "label": "咨询内容", "type": "textarea", "required": True, "placeholder": "请详细描述咨询内容"},
        {"name": "consultant_signature", "label": "咨询人签名", "type": "text", "required": True, "placeholder": "请输入咨询人签名"},
        {"name": "recorder_signature", "label": "记录人签名", "type": "text", "required": True, "placeholder": "请输入记录人签名"},
    ],
    "FZ-002": [  # 法律援助申请表
        {"name": "applicant_name", "label": "申请人姓名", "type": "text", "required": True, "placeholder": "请输入申请人姓名"},
        {"name": "applicant_gender", "label": "申请人性别", "type": "select", "required": True, "options": [{"value": "男", "label": "男"}, {"value": "女", "label": "女"}]},
        {"name": "applicant_id_no", "label": "身份证号", "type": "text", "required": True, "placeholder": "请输入身份证号"},
        {"name": "applicant_address", "label": "住址", "type": "text", "required": True, "placeholder": "请输入住址"},
        {"name": "applicant_phone", "label": "联系电话", "type": "text", "required": True, "placeholder": "请输入联系电话"},
        {"name": "economic_status", "label": "经济困难状况", "type": "textarea", "required": True, "placeholder": "请描述经济困难状况"},
        {"name": "case_brief", "label": "案情简述", "type": "textarea", "required": True, "placeholder": "请简要描述案情"},
        {"name": "application_reason", "label": "申请理由", "type": "textarea", "required": True, "placeholder": "请输入申请法律援助的理由"},
        {"name": "application_date", "label": "申请日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
        {"name": "applicant_signature", "label": "申请人签名", "type": "text", "required": True, "placeholder": "请输入申请人签名"},
    ],
    "FZ-003": [  # 授权委托书（法律援助用）
        {"name": "client_name", "label": "委托人姓名", "type": "text", "required": True, "placeholder": "请输入委托人姓名"},
        {"name": "client_id_no", "label": "委托人身份证号", "type": "text", "required": True, "placeholder": "请输入身份证号"},
        {"name": "agent_name", "label": "代理人姓名", "type": "text", "required": True, "placeholder": "请输入代理人姓名"},
        {"name": "agent_law_firm", "label": "代理人律所", "type": "text", "required": True, "placeholder": "请输入律师事务所"},
        {"name": "case_cause", "label": "案由", "type": "text", "required": True, "placeholder": "请输入案由"},
        {"name": "case_no", "label": "案号", "type": "text", "required": False, "placeholder": "请输入案号"},
        {"name": "authorization_scope", "label": "授权范围", "type": "text", "required": True, "placeholder": "请输入授权范围"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
        {"name": "client_signature", "label": "委托人签名", "type": "text", "required": True, "placeholder": "请输入委托人签名"},
    ],
    "FZ-004": [  # 经济困难状况说明表
        {"name": "applicant_name", "label": "申请人姓名", "type": "text", "required": True, "placeholder": "请输入申请人姓名"},
        {"name": "applicant_id_no", "label": "身份证号", "type": "text", "required": True, "placeholder": "请输入身份证号"},
        {"name": "applicant_address", "label": "住址", "type": "text", "required": True, "placeholder": "请输入住址"},
        {"name": "family_income", "label": "家庭收入", "type": "text", "required": True, "placeholder": "请输入家庭年收入"},
        {"name": "family_expenses", "label": "家庭支出", "type": "text", "required": True, "placeholder": "请输入家庭年支出"},
        {"name": "property_status", "label": "财产状况", "type": "textarea", "required": True, "placeholder": "请描述财产状况"},
        {"name": "debt_status", "label": "债务状况", "type": "textarea", "required": True, "placeholder": "请描述债务状况"},
        {"name": "declaration", "label": "声明", "type": "textarea", "required": True, "placeholder": "请输入声明内容"},
        {"name": "applicant_signature", "label": "申请人签名", "type": "text", "required": True, "placeholder": "请输入申请人签名"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-005": [  # 法律援助申请材料接收凭证
        {"name": "applicant_name", "label": "申请人姓名", "type": "text", "required": True, "placeholder": "请输入申请人姓名"},
        {"name": "receive_date", "label": "接收日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
        {"name": "materials_list", "label": "材料清单", "type": "array", "required": True, "item": {"type": "object", "properties": [
            {"name": "name", "label": "材料名称", "type": "text", "required": True},
            {"name": "quantity", "label": "份数", "type": "text", "required": False},
        ]}},
        {"name": "receiver_signature", "label": "接收人签名", "type": "text", "required": True, "placeholder": "请输入接收人签名"},
        {"name": "applicant_signature", "label": "申请人签名", "type": "text", "required": True, "placeholder": "请输入申请人签名"},
    ],
    "FZ-006": [  # 补充材料/说明通知书
        {"name": "applicant_name", "label": "申请人姓名", "type": "text", "required": True, "placeholder": "请输入申请人姓名"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "required_materials", "label": "需补充材料", "type": "array", "required": True, "item": {"type": "text", "label": "材料名称"}},
        {"name": "deadline", "label": "补正期限", "type": "text", "required": True, "placeholder": "请输入补正期限"},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-007": [  # 法律援助协作函
        {"name": "to_authority", "label": "致机关/单位", "type": "text", "required": True, "placeholder": "请输入致函机关/单位"},
        {"name": "case_cause", "label": "案由", "type": "text", "required": True, "placeholder": "请输入案由"},
        {"name": "case_no", "label": "案号", "type": "text", "required": False, "placeholder": "请输入案号"},
        {"name": "collaboration_content", "label": "协作内容", "type": "textarea", "required": True, "placeholder": "请输入协作内容"},
        {"name": "contact_info", "label": "联系方式", "type": "text", "required": True, "placeholder": "请输入联系方式"},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-008": [  # 法律援助审查表
        {"name": "applicant_name", "label": "申请人姓名", "type": "text", "required": True, "placeholder": "请输入申请人姓名"},
        {"name": "applicant_id_no", "label": "身份证号", "type": "text", "required": True, "placeholder": "请输入身份证号"},
        {"name": "case_brief", "label": "案情简述", "type": "textarea", "required": True, "placeholder": "请简要描述案情"},
        {"name": "economic_status_review", "label": "经济状况审查", "type": "textarea", "required": True, "placeholder": "请输入经济状况审查意见"},
        {"name": "legal_review", "label": "法律审查", "type": "textarea", "required": True, "placeholder": "请输入法律审查意见"},
        {"name": "review_opinion", "label": "审查意见", "type": "textarea", "required": True, "placeholder": "请输入审查意见"},
        {"name": "reviewer_signature", "label": "审查人签名", "type": "text", "required": True, "placeholder": "请输入审查人签名"},
        {"name": "review_date", "label": "审查日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-009": [  # 给予法律援助决定书
        {"name": "applicant_name", "label": "申请人姓名", "type": "text", "required": True, "placeholder": "请输入申请人姓名"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "decision_reason", "label": "决定理由", "type": "textarea", "required": True, "placeholder": "请输入给予法律援助的理由"},
        {"name": "assistance_type", "label": "援助类型", "type": "select", "required": True, "options": [{"value": "刑事辩护", "label": "刑事辩护"}, {"value": "民事代理", "label": "民事代理"}, {"value": "行政代理", "label": "行政代理"}]},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-010": [  # 不予法律援助决定书
        {"name": "applicant_name", "label": "申请人姓名", "type": "text", "required": True, "placeholder": "请输入申请人姓名"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "rejection_reason", "label": "不予援助理由", "type": "textarea", "required": True, "placeholder": "请输入不予法律援助的理由"},
        {"name": "appeal_right", "label": "救济权利", "type": "textarea", "required": True, "placeholder": "请输入救济权利说明"},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-011": [  # 指派通知书
        {"name": "to_law_firm", "label": "致律师事务所", "type": "text", "required": True, "placeholder": "请输入律师事务所名称"},
        {"name": "case_cause", "label": "案由", "type": "text", "required": True, "placeholder": "请输入案由"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "assigned_lawyer", "label": "指派律师", "type": "text", "required": True, "placeholder": "请输入指派律师姓名"},
        {"name": "deadline", "label": "办理期限", "type": "text", "required": True, "placeholder": "请输入办理期限"},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-012": [  # 委托代理/辩护协议
        {"name": "client_name", "label": "委托人姓名", "type": "text", "required": True, "placeholder": "请输入委托人姓名"},
        {"name": "client_id_no", "label": "委托人身份证号", "type": "text", "required": True, "placeholder": "请输入身份证号"},
        {"name": "law_firm_name", "label": "律师事务所名称", "type": "text", "required": True, "placeholder": "请输入律所名称"},
        {"name": "law_firm_address", "label": "律所地址", "type": "text", "required": True, "placeholder": "请输入律所地址"},
        {"name": "assigned_lawyer", "label": "指派律师", "type": "text", "required": True, "placeholder": "请输入指派律师姓名"},
        {"name": "case_cause", "label": "案由", "type": "text", "required": True, "placeholder": "请输入案由"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "rights_obligations", "label": "权利义务", "type": "textarea", "required": True, "placeholder": "请输入权利义务条款"},
        {"name": "agreement_date", "label": "协议日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-013": [  # 法律援助公函
        {"name": "to_authority", "label": "致机关/单位", "type": "text", "required": True, "placeholder": "请输入致函机关/单位"},
        {"name": "case_cause", "label": "案由", "type": "text", "required": True, "placeholder": "请输入案由"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "assigned_lawyer", "label": "指派律师", "type": "text", "required": True, "placeholder": "请输入指派律师姓名"},
        {"name": "authorization_scope", "label": "授权范围", "type": "text", "required": True, "placeholder": "请输入授权范围"},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-014": [  # 案件承办情况通报/报告记录
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "case_cause", "label": "案由", "type": "text", "required": True, "placeholder": "请输入案由"},
        {"name": "report_content", "label": "报告内容", "type": "textarea", "required": True, "placeholder": "请输入承办情况报告内容"},
        {"name": "reporter", "label": "报告人", "type": "text", "required": True, "placeholder": "请输入报告人姓名"},
        {"name": "report_date", "label": "报告日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
        {"name": "receiver_signature", "label": "接收人签名", "type": "text", "required": True, "placeholder": "请输入接收人签名"},
    ],
    "FZ-015": [  # 法律援助机构介绍信
        {"name": "to_authority", "label": "致机关/单位", "type": "text", "required": True, "placeholder": "请输入致函机关/单位"},
        {"name": "case_cause", "label": "案由", "type": "text", "required": True, "placeholder": "请输入案由"},
        {"name": "introduced_person", "label": "被介绍人", "type": "text", "required": True, "placeholder": "请输入被介绍人姓名"},
        {"name": "purpose", "label": "目的", "type": "text", "required": True, "placeholder": "请输入介绍目的"},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-016": [  # 更换法律援助人员申请表
        {"name": "applicant_name", "label": "申请人姓名", "type": "text", "required": True, "placeholder": "请输入申请人姓名"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "current_lawyer", "label": "当前承办律师", "type": "text", "required": True, "placeholder": "请输入当前承办律师姓名"},
        {"name": "replacement_reason", "label": "更换原因", "type": "textarea", "required": True, "placeholder": "请输入更换原因"},
        {"name": "proposed_lawyer", "label": "拟更换律师", "type": "text", "required": False, "placeholder": "请输入拟更换律师姓名"},
        {"name": "applicant_signature", "label": "申请人签名", "type": "text", "required": True, "placeholder": "请输入申请人签名"},
        {"name": "application_date", "label": "申请日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-017": [  # 更换法律援助人员通知书
        {"name": "applicant_name", "label": "申请人姓名", "type": "text", "required": True, "placeholder": "请输入申请人姓名"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "original_lawyer", "label": "原承办律师", "type": "text", "required": True, "placeholder": "请输入原承办律师姓名"},
        {"name": "new_lawyer", "label": "新承办律师", "type": "text", "required": True, "placeholder": "请输入新承办律师姓名"},
        {"name": "reason", "label": "更换原因", "type": "textarea", "required": True, "placeholder": "请输入更换原因"},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-018": [  # 终止法律援助决定书
        {"name": "applicant_name", "label": "申请人姓名", "type": "text", "required": True, "placeholder": "请输入申请人姓名"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "termination_reason", "label": "终止原因", "type": "textarea", "required": True, "placeholder": "请输入终止法律援助的原因"},
        {"name": "appeal_right", "label": "救济权利", "type": "textarea", "required": True, "placeholder": "请输入救济权利说明"},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-019": [  # 终止法律援助公函
        {"name": "to_authority", "label": "致机关/单位", "type": "text", "required": True, "placeholder": "请输入致函机关/单位"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "termination_reason", "label": "终止原因", "type": "textarea", "required": True, "placeholder": "请输入终止法律援助的原因"},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-020": [  # 法律援助异议审查决定书
        {"name": "applicant_name", "label": "申请人姓名", "type": "text", "required": True, "placeholder": "请输入申请人姓名"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "objection_content", "label": "异议内容", "type": "textarea", "required": True, "placeholder": "请输入异议内容"},
        {"name": "review_result", "label": "审查结果", "type": "textarea", "required": True, "placeholder": "请输入审查结果"},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-021": [  # 结案报告表
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "case_cause", "label": "案由", "type": "text", "required": True, "placeholder": "请输入案由"},
        {"name": "handling_process", "label": "办理过程", "type": "textarea", "required": True, "placeholder": "请描述办理过程"},
        {"name": "handling_result", "label": "办理结果", "type": "textarea", "required": True, "placeholder": "请描述办理结果"},
        {"name": "expense_settlement", "label": "费用结算", "type": "text", "required": False, "placeholder": "请输入费用结算情况"},
        {"name": "handler_signature", "label": "承办人签名", "type": "text", "required": True, "placeholder": "请输入承办人签名"},
        {"name": "closing_date", "label": "结案日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-022": [  # 送达回证
        {"name": "document_name", "label": "文书名称", "type": "text", "required": True, "placeholder": "请输入文书名称"},
        {"name": "receiver_name", "label": "接收人姓名", "type": "text", "required": True, "placeholder": "请输入接收人姓名"},
        {"name": "receiver_address", "label": "接收人地址", "type": "text", "required": True, "placeholder": "请输入接收人地址"},
        {"name": "delivery_date", "label": "送达日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
        {"name": "receiver_signature", "label": "接收人签名", "type": "text", "required": True, "placeholder": "请输入接收人签名"},
        {"name": "remarks", "label": "备注", "type": "text", "required": False, "placeholder": "请输入备注"},
    ],
    "FZ-023": [  # 法律帮助申请表
        {"name": "applicant_name", "label": "申请人姓名", "type": "text", "required": True, "placeholder": "请输入申请人姓名"},
        {"name": "applicant_id_no", "label": "身份证号", "type": "text", "required": True, "placeholder": "请输入身份证号"},
        {"name": "case_brief", "label": "案情简述", "type": "textarea", "required": True, "placeholder": "请简要描述案情"},
        {"name": "help_content", "label": "申请帮助内容", "type": "textarea", "required": True, "placeholder": "请输入申请法律帮助的内容"},
        {"name": "application_date", "label": "申请日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
        {"name": "applicant_signature", "label": "申请人签名", "type": "text", "required": True, "placeholder": "请输入申请人签名"},
    ],
    "FZ-024": [  # 值班律师提供法律帮助通知书（公安机关）
        {"name": "to_authority", "label": "致公安机关", "type": "text", "required": True, "placeholder": "请输入公安机关名称"},
        {"name": "suspect_name", "label": "犯罪嫌疑人姓名", "type": "text", "required": True, "placeholder": "请输入犯罪嫌疑人姓名"},
        {"name": "case_cause", "label": "涉嫌罪名/案由", "type": "text", "required": True, "placeholder": "请输入涉嫌罪名"},
        {"name": "assigned_lawyer", "label": "值班律师", "type": "text", "required": True, "placeholder": "请输入值班律师姓名"},
        {"name": "notification_date", "label": "通知日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-025": [  # 值班律师提供法律帮助通知书（国家安全机关）
        {"name": "to_authority", "label": "致国家安全机关", "type": "text", "required": True, "placeholder": "请输入国家安全机关名称"},
        {"name": "suspect_name", "label": "犯罪嫌疑人姓名", "type": "text", "required": True, "placeholder": "请输入犯罪嫌疑人姓名"},
        {"name": "case_cause", "label": "涉嫌罪名/案由", "type": "text", "required": True, "placeholder": "请输入涉嫌罪名"},
        {"name": "assigned_lawyer", "label": "值班律师", "type": "text", "required": True, "placeholder": "请输入值班律师姓名"},
        {"name": "notification_date", "label": "通知日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-026": [  # 值班律师提供法律帮助通知书（人民检察院）
        {"name": "to_authority", "label": "致人民检察院", "type": "text", "required": True, "placeholder": "请输入人民检察院名称"},
        {"name": "suspect_name", "label": "犯罪嫌疑人姓名", "type": "text", "required": True, "placeholder": "请输入犯罪嫌疑人姓名"},
        {"name": "case_cause", "label": "涉嫌罪名/案由", "type": "text", "required": True, "placeholder": "请输入涉嫌罪名"},
        {"name": "assigned_lawyer", "label": "值班律师", "type": "text", "required": True, "placeholder": "请输入值班律师姓名"},
        {"name": "notification_date", "label": "通知日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-027": [  # 值班律师提供法律帮助通知书（人民法院）
        {"name": "to_authority", "label": "致人民法院", "type": "text", "required": True, "placeholder": "请输入人民法院名称"},
        {"name": "suspect_name", "label": "犯罪嫌疑人/被告人姓名", "type": "text", "required": True, "placeholder": "请输入犯罪嫌疑人/被告人姓名"},
        {"name": "case_cause", "label": "涉嫌罪名/案由", "type": "text", "required": True, "placeholder": "请输入涉嫌罪名"},
        {"name": "assigned_lawyer", "label": "值班律师", "type": "text", "required": True, "placeholder": "请输入值班律师姓名"},
        {"name": "notification_date", "label": "通知日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-028": [  # 值班律师提供法律帮助情况登记表
        {"name": "lawyer_name", "label": "值班律师姓名", "type": "text", "required": True, "placeholder": "请输入律师姓名"},
        {"name": "help_date", "label": "帮助日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
        {"name": "help_content", "label": "帮助内容", "type": "textarea", "required": True, "placeholder": "请描述法律帮助内容"},
        {"name": "help_result", "label": "帮助结果", "type": "textarea", "required": True, "placeholder": "请描述帮助结果"},
        {"name": "lawyer_signature", "label": "律师签名", "type": "text", "required": True, "placeholder": "请输入律师签名"},
    ],
    "FZ-029": [  # 值班律师法律帮助工作台账
        {"name": "statistical_period", "label": "统计期间", "type": "text", "required": True, "placeholder": "请输入统计期间"},
        {"name": "total_help_count", "label": "帮助总人次", "type": "text", "required": True, "placeholder": "请输入帮助总人次"},
        {"name": "criminal_count", "label": "刑事帮助人次", "type": "text", "required": False, "placeholder": "请输入刑事帮助人次"},
        {"name": "civil_count", "label": "民事帮助人次", "type": "text", "required": False, "placeholder": "请输入民事帮助人次"},
        {"name": "administrative_count", "label": "行政帮助人次", "type": "text", "required": False, "placeholder": "请输入行政帮助人次"},
        {"name": "recorder", "label": "记录人", "type": "text", "required": True, "placeholder": "请输入记录人"},
        {"name": "record_date", "label": "记录日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-030": [  # 庭审旁听情况记录表
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "court", "label": "审理法院", "type": "text", "required": True, "placeholder": "请输入审理法院"},
        {"name": "hearing_date", "label": "开庭日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
        {"name": "performance_evaluation", "label": "出庭表现评价", "type": "textarea", "required": True, "placeholder": "请评价出庭表现"},
        {"name": "observer_signature", "label": "旁听人签名", "type": "text", "required": True, "placeholder": "请输入旁听人签名"},
        {"name": "record_date", "label": "记录日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-031": [  # 征询办案机关意见函
        {"name": "to_authority", "label": "致办案机关", "type": "text", "required": True, "placeholder": "请输入办案机关名称"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "consultation_content", "label": "征询内容", "type": "textarea", "required": True, "placeholder": "请输入征询内容"},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-032": [  # 受援人回访记录表
        {"name": "recipient_name", "label": "受援人姓名", "type": "text", "required": True, "placeholder": "请输入受援人姓名"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "service_evaluation", "label": "服务评价", "type": "textarea", "required": True, "placeholder": "请输入对法律援助服务的评价"},
        {"name": "suggestions", "label": "建议", "type": "textarea", "required": False, "placeholder": "请输入建议"},
        {"name": "interviewer_signature", "label": "回访人签名", "type": "text", "required": True, "placeholder": "请输入回访人签名"},
        {"name": "interview_date", "label": "回访日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
}

# ======== FZ律师辅助文书字段 ========
LAWYER_FIELDS = {
    "FZ-033": [  # 类案检索报告
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "case_cause", "label": "案由", "type": "text", "required": True, "placeholder": "请输入案由"},
        {"name": "retriever", "label": "检索人", "type": "text", "required": True, "placeholder": "请输入检索人姓名"},
        {"name": "retrieval_date", "label": "检索日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
        {"name": "platforms", "label": "检索平台", "type": "text", "required": True, "placeholder": "请输入检索平台"},
        {"name": "key_points", "label": "裁判要点", "type": "array", "required": True, "item": {"type": "text", "label": "裁判要点"}},
        {"name": "dispute_focus", "label": "争议焦点", "type": "textarea", "required": True, "placeholder": "请输入争议焦点"},
        {"name": "reference_analysis", "label": "参照分析", "type": "textarea", "required": True, "placeholder": "请输入参照分析"},
        {"name": "conclusion", "label": "结论", "type": "textarea", "required": True, "placeholder": "请输入检索结论"},
    ],
    "FZ-034": [  # 案件汇报提纲
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "case_cause", "label": "案由", "type": "text", "required": True, "placeholder": "请输入案由"},
        {"name": "case_basic_info", "label": "案件基本情况", "type": "textarea", "required": True, "placeholder": "请输入案件基本情况"},
        {"name": "evidence_analysis", "label": "证据分析", "type": "textarea", "required": True, "placeholder": "请输入证据分析"},
        {"name": "legal_application", "label": "法律适用", "type": "textarea", "required": True, "placeholder": "请输入法律适用分析"},
        {"name": "handling_opinions", "label": "处理意见", "type": "textarea", "required": True, "placeholder": "请输入处理意见"},
        {"name": "risks", "label": "风险提示", "type": "textarea", "required": False, "placeholder": "请输入风险提示"},
        {"name": "drafter", "label": "拟稿人", "type": "text", "required": True, "placeholder": "请输入拟稿人"},
        {"name": "draft_date", "label": "拟稿日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-035": [  # 类案批量侦查数据分析报告
        {"name": "survey_overview", "label": "调研概况", "type": "textarea", "required": True, "placeholder": "请输入调研概况"},
        {"name": "basic_data", "label": "基础数据", "type": "textarea", "required": True, "placeholder": "请输入基础数据"},
        {"name": "case_features", "label": "案件特征", "type": "textarea", "required": True, "placeholder": "请输入案件特征"},
        {"name": "problems", "label": "突出问题", "type": "array", "required": True, "item": {"type": "text", "label": "问题"}},
        {"name": "causes", "label": "成因分析", "type": "textarea", "required": True, "placeholder": "请输入成因分析"},
        {"name": "suggestions", "label": "整改建议", "type": "textarea", "required": True, "placeholder": "请输入整改建议"},
        {"name": "drafter", "label": "拟稿人", "type": "text", "required": True, "placeholder": "请输入拟稿人"},
        {"name": "draft_date", "label": "拟稿日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-036": [  # 专项侦查工作方案
        {"name": "case_brief", "label": "简要案情", "type": "textarea", "required": True, "placeholder": "请输入简要案情"},
        {"name": "case_analysis", "label": "案情分析", "type": "textarea", "required": True, "placeholder": "请输入案情分析"},
        {"name": "organization", "label": "组织分工", "type": "textarea", "required": True, "placeholder": "请输入组织分工"},
        {"name": "measures", "label": "侦查措施", "type": "array", "required": True, "item": {"type": "text", "label": "侦查措施"}},
        {"name": "timeline", "label": "时限安排", "type": "text", "required": True, "placeholder": "请输入时限安排"},
        {"name": "risk_prevention", "label": "风险防控", "type": "textarea", "required": False, "placeholder": "请输入风险防控措施"},
        {"name": "drafter", "label": "拟稿人", "type": "text", "required": True, "placeholder": "请输入拟稿人"},
        {"name": "draft_date", "label": "拟稿日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-037": [  # 审查报告（捕诉合一）
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "case_cause", "label": "案由", "type": "text", "required": True, "placeholder": "请输入案由"},
        {"name": "litigation_process", "label": "诉讼经过", "type": "textarea", "required": True, "placeholder": "请输入诉讼经过"},
        {"name": "parties_info", "label": "当事人信息", "type": "textarea", "required": True, "placeholder": "请输入当事人信息"},
        {"name": "case_occurrence", "label": "案发经过", "type": "textarea", "required": True, "placeholder": "请输入案发经过"},
        {"name": "evidence_review", "label": "证据审查", "type": "textarea", "required": True, "placeholder": "请输入证据审查意见"},
        {"name": "facts_found", "label": "查明事实", "type": "textarea", "required": True, "placeholder": "请输入查明事实"},
        {"name": "handling_opinion", "label": "处理意见", "type": "textarea", "required": True, "placeholder": "请输入处理意见"},
        {"name": "drafter", "label": "拟稿人", "type": "text", "required": True, "placeholder": "请输入拟稿人"},
        {"name": "draft_date", "label": "拟稿日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-038": [  # 书面质证意见书
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "evidence_name", "label": "质证证据名称", "type": "text", "required": True, "placeholder": "请输入证据名称"},
        {"name": "authenticity_objection", "label": "真实性异议", "type": "textarea", "required": True, "placeholder": "请输入真实性异议"},
        {"name": "legality_objection", "label": "合法性异议", "type": "textarea", "required": True, "placeholder": "请输入合法性异议"},
        {"name": "relevance_objection", "label": "关联性异议", "type": "textarea", "required": True, "placeholder": "请输入关联性异议"},
        {"name": "purpose_objection", "label": "证明目的异议", "type": "textarea", "required": True, "placeholder": "请输入证明目的异议"},
        {"name": "drafter", "label": "拟稿人", "type": "text", "required": True, "placeholder": "请输入拟稿人"},
        {"name": "draft_date", "label": "拟稿日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-039": [  # 辩护词
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "defendant_name", "label": "被告人姓名", "type": "text", "required": True, "placeholder": "请输入被告人姓名"},
        {"name": "case_cause", "label": "指控罪名", "type": "text", "required": True, "placeholder": "请输入指控罪名"},
        {"name": "defense_opinions", "label": "辩护意见", "type": "array", "required": True, "item": {"type": "object", "properties": [
            {"name": "point", "label": "辩护要点", "type": "text", "required": True},
            {"name": "detail", "label": "详细论述", "type": "textarea", "required": True},
        ]}},
        {"name": "conclusion", "label": "结论", "type": "textarea", "required": True, "placeholder": "请输入辩护结论"},
        {"name": "drafter", "label": "辩护人", "type": "text", "required": True, "placeholder": "请输入辩护人"},
        {"name": "draft_date", "label": "日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-040": [  # 公诉意见书
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "defendant_name", "label": "被告人姓名", "type": "text", "required": True, "placeholder": "请输入被告人姓名"},
        {"name": "case_cause", "label": "指控罪名", "type": "text", "required": True, "placeholder": "请输入指控罪名"},
        {"name": "court_task", "label": "出庭任务", "type": "text", "required": True, "placeholder": "请输入出庭任务"},
        {"name": "investigation_result", "label": "法庭调查结果", "type": "textarea", "required": True, "placeholder": "请输入法庭调查结果"},
        {"name": "sentencing_suggestion", "label": "量刑建议", "type": "textarea", "required": True, "placeholder": "请输入量刑建议"},
        {"name": "drafter", "label": "公诉人", "type": "text", "required": True, "placeholder": "请输入公诉人"},
        {"name": "draft_date", "label": "日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-041": [  # 不起诉理由说明书
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "suspect_name", "label": "犯罪嫌疑人姓名", "type": "text", "required": True, "placeholder": "请输入犯罪嫌疑人姓名"},
        {"name": "case_cause", "label": "涉嫌罪名", "type": "text", "required": True, "placeholder": "请输入涉嫌罪名"},
        {"name": "case_source", "label": "案件来源", "type": "text", "required": True, "placeholder": "请输入案件来源"},
        {"name": "investigation_facts", "label": "侦查机关认定事实", "type": "textarea", "required": True, "placeholder": "请输入侦查机关认定事实"},
        {"name": "review_facts", "label": "审查查明事实", "type": "textarea", "required": True, "placeholder": "请输入审查查明事实"},
        {"name": "non_prosecution_reason", "label": "不起诉理由", "type": "textarea", "required": True, "placeholder": "请输入不起诉理由"},
        {"name": "legal_basis", "label": "法律依据", "type": "textarea", "required": True, "placeholder": "请输入法律依据"},
        {"name": "drafter", "label": "拟稿人", "type": "text", "required": True, "placeholder": "请输入拟稿人"},
        {"name": "draft_date", "label": "拟稿日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-042": [  # 司法建议书
        {"name": "to_unit", "label": "主送单位", "type": "text", "required": True, "placeholder": "请输入主送单位"},
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "problem_found", "label": "发现问题", "type": "textarea", "required": True, "placeholder": "请输入发现的问题"},
        {"name": "facts", "label": "事实依据", "type": "textarea", "required": True, "placeholder": "请输入事实依据"},
        {"name": "legal_basis", "label": "法律依据", "type": "textarea", "required": True, "placeholder": "请输入法律依据"},
        {"name": "suggestions", "label": "建议内容", "type": "textarea", "required": True, "placeholder": "请输入建议内容"},
        {"name": "feedback_requirement", "label": "反馈要求", "type": "text", "required": False, "placeholder": "请输入反馈要求"},
        {"name": "issuing_authority", "label": "出具机关", "type": "text", "required": True, "placeholder": "请输入出具机关"},
        {"name": "issue_date", "label": "出具日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
    "FZ-043": [  # 律师会见笔录
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "interviewee_name", "label": "被会见人姓名", "type": "text", "required": True, "placeholder": "请输入被会见人姓名"},
        {"name": "meeting_time", "label": "会见时间", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
        {"name": "location", "label": "会见地点", "type": "text", "required": True, "placeholder": "请输入会见地点"},
        {"name": "meeting_content", "label": "会见内容", "type": "textarea", "required": True, "placeholder": "请详细记录会见内容"},
        {"name": "lawyer_signature", "label": "律师签名", "type": "text", "required": True, "placeholder": "请输入律师签名"},
        {"name": "interviewee_signature", "label": "被会见人签名", "type": "text", "required": True, "placeholder": "请输入被会见人签名"},
    ],
    "FZ-044": [  # 庭审发问提纲
        {"name": "case_no", "label": "案号", "type": "text", "required": True, "placeholder": "请输入案号"},
        {"name": "question_object", "label": "发问对象", "type": "text", "required": True, "placeholder": "请输入发问对象"},
        {"name": "questions", "label": "问题清单", "type": "array", "required": True, "item": {"type": "object", "properties": [
            {"name": "order", "label": "序号", "type": "text", "required": True},
            {"name": "content", "label": "问题内容", "type": "text", "required": True},
            {"name": "purpose", "label": "发问目的", "type": "text", "required": False},
        ]}},
        {"name": "drafter", "label": "拟稿人", "type": "text", "required": True, "placeholder": "请输入拟稿人"},
        {"name": "draft_date", "label": "拟稿日期", "type": "date", "required": True, "format": "yyyy年MM月dd日"},
    ],
}

# 合并所有FZ字段
FZ_FIELDS.update(LAWYER_FIELDS)

# ======== 输出为JSON供主脚本使用 ========
if __name__ == "__main__":
    print(json.dumps({"fz_fields": FZ_FIELDS, "defense_base": DEFENSE_BASE}, ensure_ascii=False, indent=2))
